---
name: syllabus
---

## In EC320

<br>

We start to build up the fundamentals of [causal analysis]{.blue}

<br>

But first we need to build up the necessary [Theory]{.hi},
[Tools]{.hii}, and [Skills]{.hp}

<br>

This course will focus _almost_ exclusively on a particular method 
that is common in statistics in general:

. . .

<br>

- [Ordinary Least Squares (OLS)]{.note} [(aka linear regression)]{.tiny}

---

## Coursework

* ***TODO*** Fix schedule

[Rough weekly outline:]{.hii}

:::: {.columns}

::: {.column width="50%"}
- [01:]{.hi} Introduction and review
- [02:]{.hi} The econometric problem
- [03:]{.hi} SLR estimation
- [04:]{.hi} SLR assumption
- [05:]{.hi} SLR inference
:::

::: {.column width="50%"}
- [06:]{.hi} [Midterm]{.hii}
- [07:]{.hi} MLR estimate and inference
- [08:]{.hi} Transformations
- [09:]{.hi} Quantitative variables
- [10:]{.hi} Exogeniety and final review
:::

::::

. . .

<br>

[Final:]{.hii} [Thursday, June 13 @ 08:00a](https://registrar.uoregon.edu/calendars/examinations#complete-final-exam-schedule)


# Syllabus {.inverse}

[_(click here)_](https://raw.githack.com/dyasui/EC320S24/syllabus/syllabus.pdf){.white}

---

## Course site

I use [GitHub]{.hi} to host a separate site with all the course materials

You can find a link to it [here](https://github.com/dyasui/EC320S24) or on the Canvas homepage

. . .

<br>

I use it because:

1. it is convenient for me to post slides
2. it allows me to post class materials on my website
3. acts as a secondary site in case Canvas poops out

. . .

[EVERYTHING](.hi) will be posted to both Canvas and GitHub except one thing... [the slides]{.fragment}

. . .

All zoom records will only be available on Canvas

---

## About me

Please call me [Dante]{.hii .big}

:::: {.columns}

::: {.column width="55%"}
<!--- [Office:]{.hi} [PLC 523](https://map.uoregon.edu/7c6d0ffbd)-->
<!--- [Office hours:]{.hi} After class 1:20-2:00p and F 10:00-11:00a-->
:::

::: {.column width="45%"}
- [Email:]{.hi} [dyasui@uoregon.edu](dyasui@uoregon.edu)
:::

::::

<br>

. . .

[> Metrics]{.hi .big}

- I love studying econometrics
- My first time teaching EC320 but I TAed for this class twice
- [Instructed:]{.hii} EC327 Winter 2024

---

## About me {data-visibility="uncounted"}

Please call me [Dante]{.hii .big}

:::: {.columns}

::: {.column width="55%"}
- [Office:]{.hi} [PLC 523](https://map.uoregon.edu/7c6d0ffbd)
- [Office hours:]{.hi} T & Th 4:00p-5:00p 
:::

::: {.column width="45%"}
- [Email:]{.hi} [adickin3@uoregon.edu](adickin3@uoregon.edu)
:::

::::

<br>

[> Grad school]{.hi .big}

- 3rd year Econ PhD student
- Applied topics related to migration and historical data
- Causal inference, statistical learning, and data science

---

## About me {data-visibility="uncounted"}

Please call me [Dante]{.hii .big}


[> Before grad school]{.hi .big}

- Grew up in Davis, CA
- Traveled around CA for gymnastics and quizbowl competitions in high school
- Studied Economics and Japanese at college in Portland, OR
- Prior to PhD, researched economic history and geography

---

## In EC320

An applied econometrician^[Applied econometrician = Practitioner of econometrics, e.g., analyst, consultant, data scientist.] needs a solid grasp on (at least) three areas:

1. The underlying [theory]{.hi} (assumptions, strengths, weaknesses).
1. An ability to load, aggregating, joining, visualizing [large datasets]{.hi}.
1. [Applying]{.hi} the theoretical methods to [actual data]{.hi}.

. . .

This course aims to deepen your knowledge in each of these three areas.

::: incremental
- 1: Analytical skills [([Math]{.hi-red})]{.fragment}
- 2-3: Computational tools [([ ]{.nf})]{.fragment}
:::

