---
name: math-review
---


---

## Notation

Data on a variable $X$ are a sequence of $n$ observations,
indexed by $i$: $$\{x_i: 1, \dots, n \}.$$

. . .

[Ex.]{.ex} $n = 5$

:::: {.columns}

::: {.column width="10%"}

:::

::: {.column width="35%"}

| $i$   | $x_i$   |
|-------|---------|
| 1     | 8       |
| 2     | 9       |
| 3     | 4       |
| 4     | 7       |
| 5     | 2       |
:::

::: {.column width="55%"}
<br>
<br>

- $i$ indicates the row number.

- $n$ is the number of rows.

- $x_i$ is the value of $X$ for row $i$.
:::

::::

---

## Summation

The [summation operator]{.hii} adds a sequence of numbers over an index:

$$
\sum_{i=1}^{n} x_i \equiv x_1 + x_2 + \dots + x_n.
$$

> The sum of $x_i$ from 1 to $n$.

. . .

:::: {.columns}

::: {.column width="10%"}

:::

::: {.column width="20%"}

| $i$   | $x_i$   |
|-------|---------|
| 1     | 7       |
| 2     | 4       |
| 3     | 10      |
| 4     | 3       |


:::

::: {.column width="70%"}
$$
\begin{aligned}
 \sum_{i=1}^{4} x_i = 7 + 4 + 10 + 3 = 23 \\
  \frac{1}{n} \sum_{i=1}^n x_i  \rightarrow \frac{1}{4} \sum_{i=1}^4 x_i &= \  6  
\end{aligned}
$$

:::
::::

---

## Summation {data-visibility="uncounted"}

The [summation operator]{.hii} adds a sequence of numbers over an index:

$$
\sum_{i=1}^{n} x_i \equiv x_1 + x_2 + \dots + x_n.
$$

> The sum of $x_i$ from 1 to $n$.

:::: {.columns}

::: {.column width="10%"}

:::

::: {.column width="20%"}

| $i$ | $c$ |
|-----|-----|
| 1   | 2   |
| 2   | 2   |
| 3   | 2   |
| 4   | 2   |

:::

::: {.column width="70%"}
$$
\begin{aligned}
 \sum_{i=1}^{4} x_i = 7 + 4 + 10 + 3 = 23 \\
 {\scriptsize \text{sample average}} \Bigg \{ \frac{1}{n} \sum_{i=1}^n x_i  \rightarrow \frac{1}{4} \sum_{i=1}^4 x_i &= \  6  
\end{aligned}
$$

:::
::::


---

## Summation: Rule 01

For any constant $c$, 

$$
\sum_{i=1}^{n} c = nc.
$$

. . .

:::: {.columns}

::: {.column width="10%"}

:::

::: {.column width="20%"}

| $i$ | $c$ |
|-----|-----|
| 1   | 2   |
| 2   | 2   |
| 3   | 2   |
| 4   | 2   |

:::

::: {.column width="70%"}

$$
\begin{aligned}
 \sum_{i=1}^{4} 2 &= 4 \times 2 \\
                  &= 8
\end{aligned}
$$

:::
::::


---

## Summation: Rule 02

For any constant $c$, $$\sum_{i=1}^{n} cx_i = c \sum_{i=1}^{n} x_i.$$

. . .

:::: {.columns}


::: {.column width="10%"}

:::

::: {.column width="15%"}

<br>

| $i$   | $x_i$   |
|-------|---------|
| 1     | 8       |
| 2     | 9       |
| 3     | 4       |
| 4     | 7       |
| 5     | 2       |

:::

::: {.column width="75%"}
\begin{align*}
 \sum_{i=1}^{3} 2x_i &= 2\times7 + 2\times4 + 2 \times10\\
               &= 14 + 8 + 20 = 42 \\

 2 \sum_{i=1}^{3} x_i &= 2(7 + 4 + 10) = 42
\end{align*}
:::
::::


---

## Summation: Rule 03

If $\{(x_i, y_i): 1, \dots, n \}$ is a set of $n$ pairs, and $a$ and $b$ are constants, then 

$$
\sum_{i=1}^{n} (ax_i + by_i) = a \sum_{i=1}^{n} x_i + b \sum_{i=1}^{n} y_i
$$

. . .

:::: {.columns}
::: {.column width="30%"}

| $i$   | $a$   | $x_i$   | $b$   | $y_i$   |
|-------|-------|---------|-------|---------|
| 1     | 2     | 7       | 1     | 4       |
| 2     | 2     | 4       | 1     | 2       |

:::

::: {.column width="70%"}
\begin{align}
 \sum_{i=1}^{2} (2x_i + y_i) &= 18 + 10 = 28 \\
 2 \sum_{i=1}^{2} x_i + \sum_{i=1}^{2} y_i &= 2 \times 11 + 6 = 28
\end{align}
:::
::::


---

## Summation: Caution 01

The [sum of the ratios]{.hii} is not the [ratio of the sums:]{.hp} 
$$
{\color{#81A1C1}{\sum_{i=1}^{n} x_i / y_i}} \neq \color{#B48EAD}{\left(\sum_{i=1}^{n} x_i \right) \Bigg/ \left(\sum_{i=1}^{n} y_i \right)}
$$

. . .

[Ex.]{.ex}

If $n = 2$, then $\frac{x_1}{y_1} + \frac{x_2}{y_2} \neq \frac{x_1 + x_2}{y_1 + y_2}$

---

## Summation: Caution 02

The [sum of squares]{.hii} is not the [square of the sums:]{.hp}
$$
\color{#81A1C1}{\sum_{i=1}^{n} x_i^2} \neq \color{#B48EAD}{\left(\sum_{i=1}^{n} x_i \right)^2}
$$

. . .

[Ex.]{.ex}

If $n = 2$, then $x_1^2 + x_2^2 \neq (x_1 + x_2)^2 = x_1^2 + 2x_1x_2 + x_2^2$.

---

