---
title: "Inference"
subtitle: "EC 320, Set 04"
author: "Andrew Dickinson"
date: last-modified
date-format: "Spring YYYY"
self-contained: true
format: 
  revealjs:
    theme: [default, ../styles.scss]
    monobackgroundcolor: #F5F5F5
    slide-number: true
    footer: "EC320, Set 04 | Inference"
    preview-links: auto
    code-fold: false
    code-copy: true
    highlight-style: a11y-light
    cache: true
    html-math-method: mathjax 
title-slide-attributes: 
  data-background-position: left
---

::: {.content-hidden}
$$
{{< include ../_macros.tex >}}
$$
:::

## Housekeeping

:::: {.columns}

::: {.column width="50%"}

[PS03:]{.hi}

- Due Tuesday


[Reading:]{.hi} _(up to this point)_

ItE: R, 1, [2]{.hi}

:::

::: {.column width="50%"}

[Koans]{.hi}

- K06 and K06b due Friday at 5p
- No new koans next week

:::

::::

. . .

[Midterm]{.hi-red}: Tuesday, May 7th (_next next week_)

- Review lecture next Thursday
- Old exam will be posted next week

# _Prologue_ {.inverse .note}

```{r}
#| cache: false
pacman::p_load(hrbrthemes, fastverse, tidyverse,
               magrittr, wooldridge, here, kableExtra,
               ggdag, nord, latex2exp, dagitty, viridis,
               plotly, ggforce, latex2exp, parallel, broom)


hi = nord_palettes$polarnight[3]
hii = nord_palettes$frost[3] 
hp = nord_palettes$aurora[5]
higreen = nord_palettes$aurora[4]
hiyellow = nord_palettes$aurora[3]
hiorange = nord_palettes$aurora[2]
hired = nord_palettes$aurora[1]
higrey = nord_palettes$snowstorm[1]

mytheme = theme_ipsum(base_family = "Fira Sans Book", base_size = 20) +
 theme(panel.grid.minor.x = element_blank(),
       axis.title.x = element_text(size = 18),
       axis.title.y = element_text(size = 18))

mytheme_s = mytheme + 
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.line = element_line(color = hi))

mytheme_void = theme_void(base_family = "Fira Sans Book", base_size = 20)


campus <- get(data(campus)) %>% 
  mutate(crime = round(crime/enroll*1000, 2),
         police = round(police/enroll*1000, 2)) %>% 
  filter(police < 10) %>% # remove outlier
  select(crime, police)

```

{{< include _051-prologue.qmd >}}

# _Inference_ {.inverse .note}

<!-- {{< include _052-inference.qmd >}} -->

# _Hypothesis testing_ {.inverse .note}

{{< include _053-hypothesis.qmd >}}

# _Confidence intervals_ {.inverse .note}

{{< include _054-ci.qmd >}}

# _Inference via simulation_ {.inverse .note}

{{< include _019-hytesting.qmd >}}

<!-- TODO: This lecture kind of sucked. I think a major revamp is necessary. -->

```{r}
#| include: false
#| echo: false
#| eval: false
library(renderthis)

renderthis::to_pdf(
  from = "./slides/005-inference/050-main.html",
  to = "./slides/005-inference/050-main.pdf",
  complex_slides = TRUE
)
```