---
title: "Simple Linear Regression I"
subtitle: "EC 320, Set 03"
author: "Andrew Dickinson"
date: last-modified
date-format: "Spring YYYY"
self-contained: TRUE
format: 
  revealjs:
    theme: [default, ../styles.scss]
    monobackgroundcolor: #F5F5F5
    slide-number: true
    footer: "EC320, Set 04 | Simple Linear Regression"
    preview-links: auto
    code-fold: FALSE
    # code-copy: TRUE
    highlight-style: a11y-light
    cache: FALSE
    html-math-method: mathjax 
title-slide-attributes: 
  data-background-position: left
---

## Admin

[PS01:]{.hi}

- Due Tuesday at 11:59p
- Covers remaining topics from the review and from lecture Wednesday

. . .

[Koans K01, K02, and K03:]{.hi}

- Due Friday at 5:00p

. . .

[Reading:]{.hi} _(up to this point)_

ItE: R, [1]{.hi}

<!-- # Prologue {.inverse .note} -->

```{r}
pacman::p_load(hrbrthemes, fastverse, tidyverse,
               magrittr, wooldridge, here, kableExtra,
               ggdag, nord, latex2exp, dagitty, viridis,
               emoGG, plotly)


hi = nord_palettes$polarnight[3]
hii = nord_palettes$frost[3] 
hp = nord_palettes$aurora[5]
higreen = nord_palettes$aurora[4]
hiorange = nord_palettes$aurora[2]
hired = nord_palettes$aurora[1]
higrey = nord_palettes$snowstorm[1]

mytheme = theme_ipsum(base_family = "Fira Sans Book", base_size = 20) +
 theme(panel.grid.minor.x = element_blank(),
       axis.title.x = element_text(size = 18),
       axis.title.y = element_text(size = 18))

mytheme_s = mytheme + 
  theme(panel.grid.minor.y = element_blank(),
        panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_blank(),
        axis.line = element_line(color = hi))


data = get(data(campus)) %>% 
  mutate(crime = round(crime/enroll*1000, 2),
         police = round(police/enroll*1000, 2)) %>% 
  filter(police < 10) %>% # remove outlier
  select(crime, police)
data2 = get(data(campus)) %>% 
  mutate(crime = round(crime/enroll*1000, 2),
         police = round(police/enroll*1000, 2)) %>% 
  select(crime, police)
```

{{< include _021-prologue.qmd >}}

# Regression logic {.inverse .note}

{{< include _022-logic.qmd >}}

# Simple regression model {.inverse .note}

{{< include _023-simple-reg.qmd >}}

# [Ex.]{.ex} [Effect of police on crime]{.hi-white} {.inverse}

{{< include _024-exreg.qmd >}}

# Ordinary least squares {.inverse .note}

{{< include _025-ols.qmd >}}

# Coefficient interpretation {.inverse .note}

{{< include _026-interpretation.qmd >}}

# [OLS]{.hi-white} [Ex.]{.ex} {.inverse}

{{< include _027-ex.qmd >}}


```{r}
#| include: false
#| echo: false
#| eval: false

renderthis::to_pdf(from = "./slides/002-ols/020-main.html", to = "./slides/002-ols/020-main.pdf")
```